const TYPE = {
  GET_TOKEN: 'GET_TOKEN',
  
  FETCH_CHANNELS: 'FETCH_CHANNELS',
  FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
  FETCH_CHANNELS_FAILURE: 'FETCH_CHANNELS_FAILURE',
  FETCHING_CHANNELS: 'FETCHING_CHANNELS',
  
  OPEN_CHANNEL: 'OPEN_CHANNEL',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  
  FETCH_MESSAGES: 'FETCH_MESSAGES',
  SEND_MESSAGE: 'SEND_MESSAGE'
}

//function fetchChannelsSuccess(channels){
//  
//}

